steps:
  - name: 'node'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
  - name: 'gcr.io/google-appengine/node'
    args: ['gcloud', 'app', 'deploy', 'app.yaml', '--quiet']
options:
  logging: NONE